DROP DATABASE IF EXISTS city_life_db;

CREATE DATABASE city_life_db;

USE city_life_db;


CREATE TABLE apt_search 
(
id INT NOT NULL AUTO_INCREMENT,
address VARCHAR(255) NOT NULL,
home_type VARCHAR(255) NOT NULL,
rooms VARCHAR(255) NOT NULL,
price MONEY
description VARCHAR(255) NOT NULL
PRIMARY KEY(id)
)